config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: {
    registrations: "users/registrations",
    passwords: "users/passwords"
  }
  root "pages#top"
  get '/texts/php', to: 'texts#php'
  get '/texts/:id', to: 'texts#php_show'
  resources :texts do
    resource :reads, only: [:create, :destroy]
  end
  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  resources :movies do
    resource :watches, only: [:create, :destroy]
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord
  # 1ページに表示される動画教材を定義
  PER = 8
  has_many :watches, dependent: :destroy
  has_many :watched_users, through: :watches, source: :user
  
  with_options presence: true do
    validates :genre
    validates :title
    validates :url
  end
  #movieをuserが視聴済みにしている時はtrue,していない時はfalse
  def watched_by?(user)
    watches.any?{ |watch| watch.user_id == user.id }
  end
  
  enum genre: {
    invisible: 0, # 非表示
    basic: 1,
    git: 2,
    ruby: 3,
    rails: 4,
    php: 5,
    html: 6,
    javascript: 7,
    typescript: 8,
    react: 9,
    vue: 10,
    angular: 11,
    aws: 12,
    money: 13, # マネタイズ講座
    talk: 14, # 全ての勉強会
    live: 15, # 勉強会
  }
  scope :recent, -> { where(genre: ["basic", "git", "ruby", "rails"]).order(id: :asc) }
end

app/models/read.rb
class Read < ApplicationRecord
  belongs_to :user
  belongs_to :text
end

app/models/text.rb
class Text < ApplicationRecord

  PER = 9 
  has_many :reads, dependent: :destroy
  with_options presence: true do
    validates :genre
    validates :title
    validates :content
  end

  def read_by?(user)
    reads.any?{ |read| read.user_id == user.id }
  end

  scope :recent, -> { where(genre: ["basic", "git", "ruby", "rails"]) }

  enum genre: {
    invisible: 0, # 非表示
    basic: 1,
    git: 2,
    ruby: 3,
    rails: 4,
    php: 5,
    html: 6,
    javascript: 7,
    typescript: 8,
    react: 9,
    vue: 10,
    angular: 11,
    aws: 12,
    money: 13, # マネタイズ講座
    talk: 14, # 全ての勉強会
    live: 15, # 勉強会
  }

  scope :recent, -> { where(genre: ["basic", "git", "ruby", "rails"]).order(id: :asc) }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reads, dependent: :destroy
  has_many :watches, dependent: :destroy
  has_many :watched_movies, through: :watches, source: :movie
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def self.guest
    find_or_create_by!(email: "guest@example.com") do |user|
      user.password = SecureRandom.urlsafe_base64
    end
  end
end

app/models/watch.rb
class Watch < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, except: [:top]
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @q = Movie.ransack(params[:q])
    @movies = @q.result.recent.includes(:watches).page(params[:page]).per(Movie::PER)
    page_num = @movies.current_page
    @base_level = (page_num - 1) * Movie::PER
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def top
  end
end

app/controllers/reads_controller.rb
class ReadsController < ApplicationController
  before_action :set_text

  def create
    current_user.reads.create!(text_id: @text.id)
  end

  def destroy
    text = current_user.reads.find_by(text_id: @text.id)
    text.destroy!
  end

  private

  def set_text
    @text = Text.find(params[:text_id])
  end

end

app/controllers/texts_controller.rb
class TextsController < ApplicationController

  def index
    @q = Text.ransack(params[:q])
    @texts = @q.result.recent.includes(:reads).page(params[:page]).per(Text::PER)
  end
 
 def php
    @phps = Text.where(genre: ["php"]).includes(:reads)
 end

  def php_show
    @php = Text.find(params[:id])
  end
 
  def show
    @text = Text.find(params[:id])
  end

end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  before_action :ensure_normal_user, only: :create

  def ensure_normal_user
    if params[:user][:email].downcase == "guest@example.com"
      redirect_to new_user_session_path, alert: "ゲストユーザーのパスワード再設定はできません。"
    end
  end

end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :ensure_normal_user, only: %i[update destroy]

  def ensure_normal_user
    if resource.email == "guest@example.com"
      redirect_to root_path, alert: "ゲストユーザーの更新・削除はできません。"
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    sign_in User.guest
    redirect_to root_path, notice: "ゲストユーザーとしてログインしました。"
  end
end

app/controllers/watches_controller.rb
class WatchesController < ApplicationController
  before_action :set_movie
  
  def create
    current_user.watches.create!(movie_id: @movie.id)
  end
  
  def destroy
    current_user.watches.find_by(movie_id: @movie.id).destroy!
  end
  
  private
  
  def set_movie
    @movie = Movie.find(params[:movie_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def max_width
    "mw-xl"
  end
  def full_title(page_title = '')
        team_project_48 = "チームポートフォリオ　共同開発"
        if page_title.empty?
            team_project_48
        else
            "#{ page_title } | #{ team_project_48 }"
        end
    end
end

app/helpers/markdown_helper.rb
module MarkdownHelper
  def markdown(text)
    markdown = Redcarpet::Markdown.new(html_renderer, markdown_extensions)
    markdown.render(text).html_safe
  end

  private

  def html_renderer
    ::Coderayify.new(
      filter_html: true,
      hard_wrap: true,
      link_attributes: { rel: 'nofollow', target: "_blank" }
    )
  end

  def markdown_extensions
    {
      autolink: true,
      space_after_headers: true,
      no_intra_emphasis: true,
      fenced_code_blocks: true,
      tables: true,
      hard_wrap: true,
      xhtml: true,
      lax_html_blocks: true,
      strikethrough: true
    }
  end
end

app/helpers/movies_helper.rb
module MoviesHelper
  def embed_youtube(url)
    tag.iframe(
      width: 560,
      height: 315,
      src: url,
      frameborder: 0,
      allow: "accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture",
      allowfullscreen: true
      )
  end
end

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, msg| %>
  <div class="alert alert-<%= flash_type %>" role="alert">
    <a href="#" class="close" data-dismiss="alert">x</a>
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div>
  <p>COPYRIGHT &#169; TeamPortfolio ALL RIGHTS</p>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light header-nav mw-lg">
  <%= link_to(image_tag("header_logo.png", width: '240', :alt => "ヘッダーロゴ"), root_url) %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    <ul class="navbar-nav">
      <li class="nav-item active dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Ruby
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="/texts">Ruby/Railsテキスト教材</a>
          <a class="dropdown-item" href="/movies">Ruby/Rails動画教材</a>
        </div>
      </li>
      <li class="nav-item active dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          PHP
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="/texts/php">PHPテキスト教材</a>
        </div>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item active dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            マイページ
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to "アカウント編集", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "ログアウト", destroy_user_session_path, method: :delete, data: {confirm: "ログアウトしますか？"}, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <%= link_to "ログイン", new_user_session_path, class: "nav-item nav-link active" %>
        <%= link_to "ゲストログイン", users_guest_sign_in_path, method: :post, class: "nav-item nav-link active" %>
        <%= link_to "新規登録", new_user_registration_path, class: "nav-item nav-link active" %>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag('favicon.ico') %>
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">
  </head>
  <body>
    <header class="fixed-top base-bg-color">
      <%= render "layouts/header" %>
    </header>
    <main>
      <%= render "layouts/flash" %>
      <div class="base-container <%= max_width %>">
        <%= yield %>
      </div>
      <div id="page_top" class="mb-5 mr-3"><a href="#"></a></div>
    </main>
    <footer class="base-bg-color">
      <%= render "layouts/footer" %>
    </footer>
  </body>
</html>

app/views/movies/_movie.html.erb
<div class="container-fluid">
  <div class="row">
    <% @movies.each.with_index(1) do |movie, i| %>
      <div class="col-12 col-md-6 col-lg-4">
        <div class="card border-dark mb-3">
          <div class="card-header p-0">
            <div class="embed-responsive embed-responsive-16by9">
              <p><%= embed_youtube(movie.url) %></p>
            </div>
          </div>
          <div class="card-body text-dark movie-body" style="height: 12rem;">
            <p id="movie-<%= movie.id %>">
              <% if movie.watched_by?(current_user) %>
                <%= render "watched", movie: movie %>
              <% else %>
                <%= render "not_watched", movie: movie %>
              <% end %>
            </p>
            <p class="card-text movie-title">
              Lv.<%= @base_level + i %>:<%= movie.title %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/movies/_not_watched.html.erb
<%= link_to "視聴済みにする", movie_watches_path(movie), class: 'btn btn-secondary btn-block', method: :post, remote: true %>

app/views/movies/_watched.html.erb
<%= link_to "視聴済みを解除", movie_watches_path(movie), class: 'btn btn-primary btn-block', method: :delete, remote: true %>

app/views/movies/index.html.erb
<% provide(:title, "動画")%>
<div class="base-container mw-xl">
  <div class="contents-title text-center">
    <h3>Ruby/Rails 動画</h3>
  </div>
  <form class="form-inline justify-content-center">
    <%= search_form_for @q do |f| %>
      <div class="col-2.5 align-self-center">
        <div class="form-group mx-sm-3 mb-2">
          <%= f.search_field :title_cont, class: "form-control fa_search", placeholder: "\uf002 教材を探す" %>
        </div>
      </div>
      <table>
        <tr>
          <td><%= f.submit "検索", class: "btn btn-primary mb-2" %></td>
          <td><%= link_to "戻る", :back, class: "btn btn-secondary mb-2" %></td>
        </tr>
      </table>
    <% end %>
  </form>
  <hr>
  <%= render 'movies/movie', movie: @movie %>
  <%= paginate @movies %>
</div>

app/views/pages/top.html.erb
<div class="top">

  <% provide(:title, "HOME")%>
  <div class="top_message">
    <h1>Team Portfolio</h1>
    <h2>- 4人の共同開発アプリ -</h2>
  </div>
  <div class="top_guestlogin">
    <% if user_signed_in? %>
    <% else %>
      <%= link_to "ゲストログイン（閲覧用）", users_guest_sign_in_path, method: :post, class: "top_guestlogin_btn" %>
    <% end %>
  </div>
  <div class="top_member">
    <div class="top_member_title">
      <i class="fas fa-users fa_brown"></i>
      <h2>- MEMBER -</h2>
    </div>
    <div class="top_member_content">

      <div class="top_member_content_card">
        <div class="top_member_content_card_information">
          <div class="top_member_content_card_information_img">
            <%= image_tag 'takayanagi.jpg' %>
          </div>
          <div class="top_member_content_card_information_name">
            <h2>高柳　猛</h2>
          </div>
        </div>
        <div class="top_member_content_card_link">
          <%= link_to 'https://github.com/takayanagi-takesi', class:"top_member_content_card_link_hover", target: :_blank do %>
            <%= image_tag 'github_logo.png' %>
          <% end %>
          <%= link_to 'https://twitter.com/ta57510167', class:"top_member_content_card_link_hover", target: :_blank do %>
            <%= image_tag 'twitter_logo.png' %>
          <% end %>
        </div>
      </div>
      
      <div class="top_member_content_card">
        <div class="top_member_content_card_information">
          <div class="top_member_content_card_information_img">
            <%= image_tag 'naotsugu.jpg' %>
          </div>
          <div class="top_member_content_card_information_name">
            <h2>naotsugu.k</h2>
          </div>
        </div>
        <div class="top_member_content_card_link">
          <%= link_to 'https://github.com/naotsugukaneko', class:"top_member_content_card_link_hover", target: :_blank do %>
            <%= image_tag 'github_logo.png' %>
          <% end %>
          <%= link_to 'https://twitter.com/naotsuguu_k', class:"top_member_content_card_link_hover", target: :_blank do %>
            <%= image_tag 'twitter_logo.png' %>
          <% end %>
          <%= link_to 'https://www.wantedly.com/id/naotsugu_kaneko',class:"top_member_content_card_link_hover", target: :_blank do %>
            <%= image_tag 'wantedly_logo.png' %>
          <% end %>
        </div>
      </div>

      <div class="top_member_content_card">
        <div class="top_member_content_card_information">
          <div class="top_member_content_card_information_img miho">
            <%= image_tag 'miho.jpg' %>
          </div>
          <div class="top_member_content_card_information_name">
            <h2>みほ</h2>
          </div>
        </div>
        <div class="top_member_content_card_link">
          <%= link_to 'https://github.com/mihomatsui', class:"top_member_content_card_link_hover", target: :_blank do %>
            <%= image_tag 'github_logo.png' %>
          <% end %>
          <%= link_to 'https://twitter.com/mihooo_24', class:"top_member_content_card_link_hover", target: :_blank do %>
            <%= image_tag 'twitter_logo.png' %>
          <% end %>
          <%= link_to 'https://www.wantedly.com/id/miho_matsui_m',class:"top_member_content_card_link_hover", target: :_blank do %>
            <%= image_tag 'wantedly_logo.png' %>
          <% end %>
        </div>
      </div>

      <div class="top_member_content_card">
        <div class="top_member_content_card_information">
          <div class="top_member_content_card_information_img">
            <%= image_tag 'uki.jpg' %>
          </div>
          <div class="top_member_content_card_information_name">
            <h2>うっき</h2>
          </div>
        </div>
        <div class="top_member_content_card_link">
          <%= link_to 'https://github.com/itstoasted-0', class:"top_member_content_card_link_hover", target: :_blank do %>
            <%= image_tag 'github_logo.png' %>
          <% end %>
          <%= link_to 'https://twitter.com/itstoast_one', class:"top_member_content_card_link_hover", target: :_blank do %>
            <%= image_tag 'twitter_logo.png' %>
          <% end %>
          <%= link_to 'https://www.wantedly.com/id/uki',class:"top_member_content_card_link_hover", target: :_blank do %>
            <%= image_tag 'wantedly_logo.png' %>
          <% end %>
        </div>
      </div>


    </div>
  </div>

  <div class="top_source">
    <div class="top_source_title">
      <i class="fas fa-code fa_brown"></i>
      <h2>- SOURCE CODE -</h2>
    </div>
    <div class="top_source_content">
      <i class="fab fa-github fa_git"></i><%= link_to "GitHub", "https://github.com/yanbaru-expert/team_project_48", class:"top_source_link", target: :_blank %>
    </div>
  </div>
  
</div>

app/views/reads/create.js.erb
document.getElementById('text-<%= @text.id %>').innerHTML = '<%= j render("texts/read", text: @text) %>'

app/views/reads/destroy.js.erb
document.getElementById('text-<%= @text.id %>').innerHTML = '<%= j render("texts/not_read", text: @text) %>'

app/views/texts/_not_read.html.erb
<%= link_to "読破済みにする", text_reads_path(text), method: :post, remote: true, class: "btn btn-secondary btn-block" %>

app/views/texts/_read.html.erb
<%= link_to "読破済みを解除", text_reads_path(text), method: :delete, remote: true, class: "btn btn-primary btn-block" %>

app/views/texts/_text.html.erb
<div class="container-fluid">
  <div class="row">
    <% @texts.each.with_index(1) do |text| %>
      <div class="col-12 col-md-6 col-lg-4 text-card-container">
        <div class="card content-card border-dark mb-3">
          <%= link_to text_path(text.id), class:"abc" do %>
            <div class="card-header p-0">
              <img class="card-img-top img-fluid" src="https://d5izmuz0mcjzz.cloudfront.net/texts/no_image.jpg">
            </div>
            <div class="card-body text-dark text-card-body">
              <p id="text-<%= text.id %>">
              <% if text.read_by?(current_user) %>
                <%= render "read", text: text.id %>
              <% else %>
                <%= render "not_read", text: text.id %>
              <% end %>
              </p>
              <p class="card-text text-title"><%= text.title %></p>
              <p>【<%= text.genre_i18n %>】</p>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/texts/index.html.erb
<% provide(:title, "テキスト")%>
<div class="base-container mw-xl">
  <div class="contents-title text-center">
    <h3>Ruby/Rails テキスト</h3>
  </div>
  <form class="form-inline justify-content-center">
      <%= search_form_for @q do |f| %>
        <div class="col-2.5 align-self-center">
          <div class="form-group mx-sm-3 mb-2">
            <%= f.search_field :title_cont, class: "form-control fa_search", placeholder: "\uf002 教材を探す" %>
          </div>
        </div>
        <table>
          <tr>
            <td><%= f.submit "検索", class: "btn btn-primary mb-2" %></td>
            <td><%= link_to "戻る", :back, class: "btn btn-secondary mb-2" %></td>
          </tr>
        </table>
      <% end %>
    </form>
    <hr>
    <%= render 'texts/text', text: @text %>
    <%= paginate @texts %>
</div>

app/views/texts/php.html.erb
<% provide(:title, "テキスト")%>
<div class="contents-title text-center">
  <h3>PHP テキスト</h3>
</div>
<div class="container-fluid">
  <div class="row">
    <% @phps.each.with_index(1) do |php| %>
      <div class="col-12 col-md-6 col-lg-4 text-card-container">
        <div class="card content-card border-dark mb-3">
          <%= link_to "/texts/#{php.id}", class:"abc" do %>
            <div class="card-header p-0">
              <img class="card-img-top img-fluid" src="https://d5izmuz0mcjzz.cloudfront.net/texts/no_image.jpg">
            </div>
            <div class="card-body text-dark text-card-body">
              <p class="card-text text-title"><%= php.title %></p>
              <p>【<%= php.genre_i18n %>】</p>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/texts/php_show.html.erb
<p>
  <%= markdown(@php.title) %>
  <%= markdown(@php.content) %>
</p>

app/views/texts/show.html.erb
<p>
  <%= markdown(@text.title) %>
  <%= markdown(@text.content) %>
</p>

app/views/watches/create.js.erb
document.getElementById('movie-<%= @movie.id %>').innerHTML = '<%= j render("movies/watched", movie: @movie) %>'

app/views/watches/destroy.js.erb
document.getElementById('movie-<%= @movie.id %>').innerHTML = '<%= j render("movies/not_watched", movie: @movie) %>'